project:
  type: book

book:
  title: "Аналіз автомобільного ринку України"
  subtitle: "Фінальний проєкт до курсу 'Python for Data Science' від StartUp IT Academy"
  author: "Ігор Мірошниченко"
  favicon: cover.png
  date: today
  date-format: iso
  sidebar: 
    logo: cover.png
    search: true
  chapters:
    - index.qmd
    - eda.qmd
    - model.qmd

language: _language-ukr.yml

bibliography: references.bib

format:
  html:
    # df-print: kable
    theme:
      light: cosmo
      dark: superhero

execute:
  cache: true
  warning: false
  message: false



